development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: blog_master_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: blog_master_production
